<nav>
    <ul>
        <li><a class="menu" href="index.php">HOME</a></li>
        <li><a class="menu" href="product.php">PRODUCT</a></li>
        <li><a class="menu" href="enquire.php">ENQUIRE</a></li>
        <li><a class="menu" href="about.php">ABOUT</a></li>
        <li><a class="menu" href="enhancements.php">ENHANCEMENTS</a></li>
        <li><a class="menu" href="manager.php">MANAGE</a></li>
    </ul>
</nav>